### ISSUE TITLE
Nvidia OSS Drivers Require OpenRmEnableUnsupportedGpus=1 For Certain GPUs

### ISSUE THREAD

**Issue by druyang** [siderolabs/extensions#114]
System: 

Talos: v1.3.3
K8s: 1.26.1
GPU: RTX 2080S
Nvidia driver versions: 
nvidia-open-gpu-kernel-modules:515.65.01-v1.3.3
nvidia-container-toolkit:515.65.01-v1.11.0

I followed the directions in the documentations for OSS drivers (including creating the runtime and verifying the drivers were successfully installed). 

When I run the following command `helm install nvidia-device-plugin nvdp/nvidia-device-plugin --version=0.11.0 --set=runtimeClassName=nvidia` (to enable the nvidia device plugin) I get the following in the logs on the node: 

```
Open nvidia.ko is only ready for use on Data Center GPUs. 
To force use of Open nvidia.ko on other GPUs, see the 
'OpenRmEnableUnsupportedGpus' kernel module parameter described
in the README 
GPU 0000:07:00.0: RmInitAdapter failed!
```

Additionally the pod fails to start in k8s. 

I found this is due to the following: because I'm not running a datacenter GPU I need to run: 

 ```
   modprobe nvidia NVreg_OpenRmEnableUnsupportedGpus=1

or, in an /etc/modprobe.d/ configuration file:

    options nvidia NVreg_OpenRmEnableUnsupportedGpus=1

```

In fact the readme says the following (it appears this is needed for support on many GPUs) : 
https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus

> To enable use of the open kernel modules on GeForce and Workstation GPUs, set the "NVreg_OpenRmEnableUnsupportedGpus" nvidia.ko kernel module parameter to 1. For more details, see the NVIDIA GPU driver end user README here:

However, I'm not sure how to do this via the TalosCLI.

Would it be possible to support this feature in the future on the OSS drivers? Is there anyway to set that parameter on extension install or have it as a talos feature? I would be happy to implement it but may need a pointer in the right direction.

**Comment by frezbo** [comment]
The talos machineconfig supports setting module parameters https://www.talos.dev/v1.3/reference/configuration/#kernelmoduleconfig

This is not documented in the nvidia talos docs as the gpu support in oss drivers is alpha
