### ISSUE TITLE
Thunderbolt extension

### ISSUE THREAD

**Issue by spammads** [siderolabs/extensions#165]
Would be great if Sidero could provide an extension to enable Thunderbolt.
Thanks for the great work.

**Comment by spammads** [comment]
Thanks Igor, Frezbo & Team Talos!

**Comment by spammads** [comment]
Just one question – should I be able to already use this with 1.4.7.?
I know extension-version is 1.5.0. but maybe I am lucky?!
Thanks for the clarification.

**Comment by smira** [comment]
This won't be available with 1.4.x, as the kernel modules are not built for 1.4.x

**Comment by spammads** [comment]
Thanks for the Info. I will wait. Looking forward to this.
