### ISSUE TITLE
[nvidia-container-toolkit=530.41.03-v1.12.1] [talos=v1.4.5] crash on container creation when NVIDIA_DRIVER_CAPABILITIES contains "graphics"

### ISSUE THREAD

**Issue by Kolpa** [siderolabs/extensions#171]
I'm not 100% sure if this is the right place to report the issue, feel free to point me in the right direction if not :)

## My setup:
I am running a 2 node cluster based on talos 1.4.5 and i've enabled the nvidia container toolkit extension by following the [official talos tutorial](https://www.talos.dev/v1.4/talos-guides/configuration/nvidia-gpu-proprietary/#upgrading-talos-and-enabling-the-nvidia-modules-and-the-system-extension) (changing all mentions of talos version `v1.4.4` to `v1.4.5` and using version `v0.14.0` of the nvidia device plugin)

The nodes both contain a RTX 2080 GPU

## The issue:
All conventional cuda based container workloads i've tested run without any problems, `nvidia-smi` from inside of a container also reports the proper gpu information.

whenever i add `graphics` to the `NVIDIA_DRIVER_CAPABILITIES` env variable container creation fails with the following status:
```
failed to create containerd task: 
failed to create shim task: 
OCI runtime create failed: 
failed to create NVIDIA Container Runtime: 
failed to construct OCI spec modifier: 
failed to construct discoverer: 
failed to create mounts discoverer: 
failed to construct library locator: 
error loading ldcache: 
open /etc/ld.so.cache: no such file or directory: unknown
```

i am honestly at a loss here, if anyone has any input why this might be happening i would greatly appreciate any help

**Comment by Kolpa** [comment]
I've also noticed the dev documentation for the extensions references a patch to the ldcache resolver file which i cannot find in the actual repository: https://github.com/siderolabs/extensions/blob/main/nvidia-gpu/nvidia-container-toolkit/DEVELOPMENT.md#patches

**Comment by frezbo** [comment]
Some patches got merged upstream, will take a look at this next week

**Comment by maxpain** [comment]
Any updates? I have the same problem

**Comment by maxpain** [comment]
Any ETA or possible workarounds?

**Comment by smira** [comment]
You can do a fix, perform some testing and submit a PR to speed up things. 

Otherwise we'll get to it as soon as we can, no ETA is available atm.

**Comment by maxpain** [comment]
`nvc_ldcache.c.patch` was deleted in this commit
https://github.com/siderolabs/extensions/commit/93a7a0df54362a4279eb5cf9fc83c1f3023e9648

**Comment by frezbo** [comment]
> `nvc_ldcache.c.patch` was deleted in this commit [93a7a0d](https://github.com/siderolabs/extensions/commit/93a7a0df54362a4279eb5cf9fc83c1f3023e9648)

it was removed since it was fixed upstream https://gitlab.com/nvidia/container-toolkit/libnvidia-container/-/issues/1

You're looking into a different code path probably.

**Comment by frezbo** [comment]
> As I understand, nvidia-container-toolkit by default [expects](https://github.com/NVIDIA/nvidia-container-toolkit/blob/v1.12.1/internal/ldcache/ldcache.go#L35) ld.so.cache to be in the /etc directory, but in Talos this file is located at /usr/local/glibc/etc/ld.so.cache.

This is not correct, the commands gets executed inside the workload container, not the host, so it's `/etc` is correct path.

**Comment by maxpain** [comment]
> > As I understand, nvidia-container-toolkit by default [expects](https://github.com/NVIDIA/nvidia-container-toolkit/blob/v1.12.1/internal/ldcache/ldcache.go#L35) ld.so.cache to be in the /etc directory, but in Talos this file is located at /usr/local/glibc/etc/ld.so.cache.
> 
> This is not correct, the commands gets executed inside the workload container, not the host, so it's `/etc` is correct path.

`error loading ldcache` error goes from [NewLibraryLocator](https://github.com/NVIDIA/nvidia-container-toolkit/blob/v1.12.1/internal/lookup/library.go#L36C6-L36C23), which is used by [NewGraphicsMountsDiscoverer](https://github.com/NVIDIA/nvidia-container-toolkit/blob/v1.12.1/internal/discover/graphics.go#L56C8-L56C8), which is a part of `nvidia-container-runtime`. As I understand correctly, `nvidia-container-runtime` gets executed on the host.

**Comment by maxpain** [comment]
> As I understand, `nvidia-container-toolkit` by default [expects](https://github.com/NVIDIA/nvidia-container-toolkit/blob/v1.12.1/internal/ldcache/ldcache.go#L35) ld.so.cache to be in the `/etc` directory, but in Talos this file is located at `/usr/local/glibc/etc/ld.so.cache`. I changed the path and now getting another error:
> 
> ```
> Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: fork/exec /usr/bin/nvidia-ctk: no such file or directory: unknown
> ```

After this modification I also see these errors in `/var/log/nvidia-container-runtime.log`:
```
{"level":"warning","msg":"Could not locate libnvidia-egl-gbm.so: 64-bit library libnvidia-egl-gbm.so not found","time":"2023-07-08T10:09:31Z"}
{"level":"warning","msg":"Could not locate glvnd/egl_vendor.d/10_nvidia.json: pattern glvnd/egl_vendor.d/10_nvidia.json not found","time":"2023-07-08T10:09:31Z"}
{"level":"warning","msg":"Could not locate vulkan/icd.d/nvidia_icd.json: pattern vulkan/icd.d/nvidia_icd.json not found","time":"2023-07-08T10:09:31Z"}
{"level":"warning","msg":"Could not locate vulkan/implicit_layer.d/nvidia_layers.json: pattern vulkan/implicit_layer.d/nvidia_layers.json not found","time":"2023-07-08T10:09:31Z"}
{"level":"warning","msg":"Could not locate egl/egl_external_platform.d/15_nvidia_gbm.json: pattern egl/egl_external_platform.d/15_nvidia_gbm.json not found","time":"2023-07-08T10:09:31Z"}
{"level":"warning","msg":"Could not locate egl/egl_external_platform.d/10_nvidia_wayland.json: pattern egl/egl_external_platform.d/10_nvidia_wayland.json not found","time":"2023-07-08T10:09:31Z"}
```

**Comment by maxpain** [comment]
Besides changing ldcache path, It seems we also need to copy `nvidia-ctk` to the rootfs [here](https://github.com/siderolabs/extensions/blob/v1.4.6/nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/pkg.yaml#L48).
```bash
cp ./nvidia-ctk /rootfs/usr/local/bin/nvidia-ctk
```

Now my container with `NVIDIA_DRIVER_CAPABILITIES=graphics` starts without errors.

**Comment by maxpain** [comment]
I'm trying to run a headless Vulkan/OpenGL application.
As I see [nvidia-container-toolkit v1.12.0](https://github.com/NVIDIA/nvidia-container-toolkit/releases/tag/v1.12.0) started injection [appropriate libraries and config files](https://github.com/NVIDIA/nvidia-container-toolkit/blob/v1.12.1/internal/discover/graphics.go#L78C12-L84C3) from the host to the container, but we have two problems here:

1. We need to remove `--no-opengl-files` and `--no-install-libglvnd` flags [here](https://github.com/siderolabs/extensions/blob/v1.4.6/nvidia-gpu/nvidia-container-toolkit/nvidia-pkgs/pkg.yaml#L49-L53).
2. After Nvidia driver installation, we can't move these OpenGL/Vulkan libraries and files to the `/etc` and `/usr/share` folders. We can only use `/usr/local/share` in Talos. I tried to make a patch for [this code](https://github.com/NVIDIA/nvidia-container-toolkit/blob/v1.12.1/internal/discover/graphics.go#L75) and changed it to `/usr/local/share`, but after that `nvidia-container-runtime` is mounting these files to `/usr/local/share` inside a container, which is the wrong location for container applications.

**Comment by frezbo** [comment]
Thank you so much for looking into it:

> error loading ldcache error goes from [NewLibraryLocator](https://github.com/NVIDIA/nvidia-container-toolkit/blob/v1.12.1/internal/lookup/library.go#L36C6-L36C23), which is used by [NewGraphicsMountsDiscoverer](https://github.com/NVIDIA/nvidia-container-toolkit/blob/v1.12.1/internal/discover/graphics.go#L56C8-L56C8), which is a part of nvidia-container-runtime. As I understand correctly, nvidia-container-runtime gets executed on the host.

Seems I am wrong. I probably confused this with code that gets executed by the runtime inside container (which also uses libc :sweat_smile: )

But i've a little confusion, if we directly execute `ldconfig` it should look into the path that is used in talos. I guess we just need to add a custom search path here: https://github.com/NVIDIA/nvidia-container-toolkit/blob/v1.12.1/internal/discover/graphics.go#L75 (didn't look too deep).

> We need to remove --no-opengl-files and --no-install-libglvnd flags during Nvidia driver installation [here](https://github.com/siderolabs/extensions/blob/v1.4.6/nvidia-gpu/nvidia-container-toolkit/nvidia-pkgs/pkg.yaml#L49-L53).

This can be done, it was added just to drop the extension size

> After Nvidia driver installation, we can't move these OpenGL/Vulkan libraries and files to the /etc and /usr/share folders. We can only use /usr/local/share in Talos. I tried to make a patch for [this code](https://github.com/NVIDIA/nvidia-container-toolkit/blob/v1.12.1/internal/discover/graphics.go#L75) and changed it to /usr/local/share, but after that nvidia-container-runtime is mounting these files to /usr/local/share inside a container, which is the wrong location for container applications, because they expect /etc and /usr/share directories.

We could add new allowlist paths for these since it's standard for OpenGL/Vulkan i guess, (explicit like `/etc/opengl` or something)

**Comment by frezbo** [comment]
do you have a public image I can test this against?

**Comment by maxpain** [comment]
@frezbo Yes. `ghcr.io/gameflare/talos/nvidia-container-toolkit:530.41.03-v1.12.1`

**Comment by frezbo** [comment]
i meant not the toolkit, some image to test the vulkan/opengl usage

**Comment by maxpain** [comment]
ah, you can just use a regular ubuntu:23.04 and do `apt install vulkan-tools`, then `vulkaninfo --summary`

**Comment by frezbo** [comment]
@maxpain does this look good?

```bash
oot@cuda-test:/# vulkaninfo --summary
ERROR: [Loader Message] Code 0 : libXext.so.6: cannot open shared object file: No such file or directory
ERROR: [Loader Message] Code 0 : loader_icd_scan: Failed loading library associated with ICD JSON libGLX_nvidia.so.0. Ignoring this JSON
'DISPLAY' environment variable not set... skipping surface info
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.239


Instance Extensions: count = 21
-------------------------------
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_EXT_swapchain_colorspace            : extension revision 4
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_portability_enumeration         : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6

Instance Layers: count = 4
--------------------------
VK_LAYER_INTEL_nullhw       INTEL NULL HW                1.1.73   version 1
VK_LAYER_MESA_device_select Linux device selection layer 1.3.211  version 1
VK_LAYER_MESA_overlay       Mesa Overlay layer           1.3.211  version 1
VK_LAYER_NV_optimus         NVIDIA Optimus layer         1.3.242  version 1

Devices:
========
GPU0:
	apiVersion         = 1.3.238
	driverVersion      = 0.0.1
	vendorID           = 0x10005
	deviceID           = 0x0000
	deviceType         = PHYSICAL_DEVICE_TYPE_CPU
	deviceName         = llvmpipe (LLVM 15.0.7, 256 bits)
	driverID           = DRIVER_ID_MESA_LLVMPIPE
	driverName         = llvmpipe
	driverInfo         = Mesa 23.0.4-0ubuntu1~23.04.1 (LLVM 15.0.7)
	conformanceVersion = 1.3.1.1
	deviceUUID         = 6d657361-3233-2e30-2e34-2d3075627500
	driverUUID         = 6c6c766d-7069-7065-5555-494400000000
root@cuda-test:/# 

```

**Comment by frezbo** [comment]
Okay, this needed quite a few more changes, running nvidia-persistenced in persistence mode, adding the xorg libraries and copying over the /usr/share and /etc/vulkan files also adding mesa-utils package, after that I get this:

```bash
root@cuda-test:/# vulkaninfo --summary
'DISPLAY' environment variable not set... skipping surface info
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.239


Instance Extensions: count = 21
-------------------------------
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_EXT_swapchain_colorspace            : extension revision 4
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_portability_enumeration         : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6

Instance Layers: count = 4
--------------------------
VK_LAYER_INTEL_nullhw       INTEL NULL HW                1.1.73   version 1
VK_LAYER_MESA_device_select Linux device selection layer 1.3.211  version 1
VK_LAYER_MESA_overlay       Mesa Overlay layer           1.3.211  version 1
VK_LAYER_NV_optimus         NVIDIA Optimus layer         1.3.242  version 1

Devices:
========
GPU0:
	apiVersion         = 1.3.242
	driverVersion      = 535.54.3.192
	vendorID           = 0x10de
	deviceID           = 0x1eb8
	deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
	deviceName         = Tesla T4
	driverID           = DRIVER_ID_NVIDIA_PROPRIETARY
	driverName         = NVIDIA
	driverInfo         = 535.54.03
	conformanceVersion = 1.3.5.0
	deviceUUID         = 1a6de3cc-fc07-e86f-e24e-48722ca24111
	driverUUID         = 8b72f8cf-fcf7-59af-b250-edf6b04fc087
GPU1:
	apiVersion         = 1.3.238
	driverVersion      = 0.0.1
	vendorID           = 0x10005
	deviceID           = 0x0000
	deviceType         = PHYSICAL_DEVICE_TYPE_CPU
	deviceName         = llvmpipe (LLVM 15.0.7, 256 bits)
	driverID           = DRIVER_ID_MESA_LLVMPIPE
	driverName         = llvmpipe
	driverInfo         = Mesa 23.0.4-0ubuntu1~23.04.1 (LLVM 15.0.7)
	conformanceVersion = 1.3.1.1
	deviceUUID         = 6d657361-3233-2e30-2e34-2d3075627500
	driverUUID         = 6c6c766d-7069-7065-5555-494400000000
root@cuda-test:/# 

```

**Comment by frezbo** [comment]
> @frezbo What about other fixes?

you mean the one in extensions, I've a testing it currently
