### ISSUE TITLE
Cannot use iscsi-tools to mount a PV

### ISSUE THREAD

**Issue by sbogomolov** [siderolabs/extensions#172]
I'm trying to create a PV using iSCSI target on my NAS. I'm using Talos v1.4.5 and iscsi-tools v0.1.4. I can confirm that `iscsiadm` and friends are present on the host under `/usr/local/sbin`. I've created PV and PVC. When Pod using that PVC is starting, it cannot mount the PV. The error message from `kubelet` says that it cannot find the binary in $PATH.

I've checked the k8s source code to see where that error is coming from and saw that it tries to use `iscsiadm`. I assumed that this is the binary it cannot find. I've tried adding `/use/local/sbin` to `extraMounts` for `kubelet`, but that did not help. What else can I try?

**Comment by sbogomolov** [comment]
I have made progress. I've built a custom `kubelet` image with this script as `/usr/local/sbin/iscsiadm`:
```bash
#!/bin/sh

iscsid_pid=$(pgrep iscsid)
nsenter --mount="/proc/${iscsid_pid}/ns/mnt" --net="/proc/${iscsid_pid}/ns/net" -- /usr/local/sbin/iscsiadm "$@"
```

At this point the error about not finding binary in $PATH is gone. In `ext-iscsid` service logs I see good news:
```
k8s-worker-02: iscsid: Connection1:0 to [target: iqn.2000-01.com.synology:nas.Target-K8S.2edf3217d57, portal: 192.168.70.20,3260] through [iface: default] is operational now
```

Unfortunately, this is not a success story yet. When trying to create a Pod I see the following error:
```
MountVolume.WaitForAttach failed for volume "nas-config-pv" : failed to get any path for iscsi disk, last err seen:
Timed out waiting for device at path /dev/disk/by-path/ip-192.168.70.20:3260-iscsi-iqn.2000-01.com.synology:nas.Target-K8S.2edf3217d57-lun-0 after 30s
```
And indeed, that symlink does not exist. Also in `/dev` I see only sda and sdb, which are physical drives on the host. What am I missing? Do I need to provide more binaries to `kubelet`? Is `iscsiadm` not enough?

**Comment by frezbo** [comment]
This is all due to the fact that kubelet runs as a container in Talos, from the code, it seems kubelet has permissions, but i believe this is failing because `/dev/disk` is probably not accessible inside kubelet namespace and the symlink only is on host. I don't think we can fully support kubelet with iscsi since kubelet assumes a lot of binaries are present on host (kubelet does a lot of exec on binaries)

**Comment by sbogomolov** [comment]
Thanks for the reply @frezbo. In this case kubelet was executing `iscaiadm` in the namespace of `iscsid` using `nsenter`. This trick was described in Talos docs on order to make OpenEBS Jiva work [here](https://www.talos.dev/v1.4/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva/). The same trick for Synology CSI [here](https://www.talos.dev/v1.4/kubernetes-guides/configuration/synology-csi/) (the actual trick is [here](https://github.com/zebernst/synology-csi-talos/blob/0f0fd2db2069e2c9977ac35423a6aba7ec9c5f10/Dockerfile#L41)). In these examples `/dev` is not directly accessible to the CSI containers. I assumed that the usage of `iscsid`'s mount namespace does the trick for them and should do the trick for `kubelet`.

It did not :) Is `kubelet` different in some ways?

**Comment by frezbo** [comment]
There's a lot to dig into here, the iscsi extension has a writable sysfs which is required for creating the `/dev/*` iscsi devices, but the ~kubelet only has a readable sysfs (but in theory it shouldn't matter since iscsi has writable sysfs and it's the one doing it)~

I think I figured out while writing this, so kubelet has bind mounts for `/sys` , but i think i only sees what was there initially when it started (hmm that's confusing, I need to look into it more).

Another thing could be that the sys `/dev/disk` devices take some time to be populated and kubelet triues way earlier (thinking there's a udevd rule for the same). Does the device show up on the host?

`talosctl ls /dev/disk-<path>` ?

**Comment by sbogomolov** [comment]
Nope, the disk never appears on the host. The `/dev/disk/by-path` and `/dev/sd*` only show physical disks.

**Comment by sbogomolov** [comment]
Is there a way to "exec" into the kubelet container?

**Comment by frezbo** [comment]
> Is there a way to "exec" into the kubelet container?

it probably doesn't have a shell, https://github.com/siderolabs/kubelet/blob/main/Dockerfile#L31

**Comment by frezbo** [comment]
> It looks like it should have `bash`. https://github.com/siderolabs/kubelet/blob/719ff8237668442e47eb2f7eec63a405ee5019e6/Dockerfile#L35
> 
> I would not know how to exec into it anyway though. Maybe I could run this container in a pod with its entry point overridden... I'd need to figure out all the exact parameters to make sure that the permissions are the same. Doesn't sound like a walk in a park.

Sent you a DM in Talos Community slack

**Comment by frezbo** [comment]
Further tracked here: https://github.com/kubernetes/kubernetes/pull/118807

**Comment by sbogomolov** [comment]
I have taken another look at k8s logic and realised that I have missed something. After successfull login, it does manually scan, but only a specific LUN. So in my case the problem was wrong LUN number. Synology does not show it in the UI, and I assumed it to be 0. It was 1.

Bottom line: the only modification required was a custom kubelet image with the `iscsiadm` script. Similar trick is described in the Talos docs for OpenEBS Jiva and Synology CSI.

Since the modification is very small, it does not break anything and make ISCSI PVs work, would it make sense to take it upstream? I can prepare a PR for `kubelet` image if there is a chance of it being merged.

**Comment by frezbo** [comment]
> I have taken another look at k8s logic and realised that I have missed something. After successfull login, it does manually scan, but only a specific LUN. So in my case the problem was wrong LUN number. Synology does not show it in the UI, and I assumed it to be 0. It was 1.

nice find

> Since the modification is very small, it does not break anything and makes ISCSI PVs work, would it make sense to take it upstream? I can prepare a PR for kubelet image if there is a chance of it being merged.

I'm not so sure about that, would need to discuss internally

**Comment by sbogomolov** [comment]
Fixed with https://github.com/siderolabs/kubelet/pull/74.
