### ISSUE TITLE
[drbd] error loading module \x5c"drbd\x5c": module not found

### ISSUE THREAD

**Issue by walnuss0815** [siderolabs/extensions#187]
Hi all,

I've deployed a cluster using Talos via the Terraform provider. Currently the cluster has only a single node. Not I am trying to set up the piraeus-operator according to this how to https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/how-to/talos.md. I already have adapted the machine config patch to the following:
```yaml
machine:
  install:
    extensions:
      - image: ghcr.io/siderolabs/drbd:9.2.4-v1.4.6
  kernel:
    modules:
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: drbd_transport_tcp
```

Executing the two commands for validation returned the following:

`talosctl  read /proc/modules`
```
virtio_balloon 24576 - - Live 0xffffffffc02bf000
virtio_pci 24576 - - Live 0xffffffffc02a2000
virtio_pci_legacy_dev 16384 - - Live 0xffffffffc0292000
virtio_pci_modern_dev 16384 - - Live 0xffffffffc027a000
```

`talosctl read /sys/module/drbd/parameters/usermode_helper`
```
1 error occurred:
 rpc error: code = Unknown desc = stat /sys/module/drbd/parameters/usermode_helper: no such file or directory
```

So it looks like something is wrong. So I have checked the logs which contained the following two lines:
`talosctl dmesg`
```
REMOVED: user: warning: [2023-07-25T10:02:44.873296699Z]: [talos] apply config request: mode auto(no_reboot)
REMOVED: user: warning: [2023-07-25T10:03:13.119427699Z]: [talos] controller failed {"component": "controller-runtime", "controller": "runtime.KernelModuleSpecController", "error": "error loading module \x5c"drbd\x5c": module not found"}
```

`error loading module \x5c"drbd\x5c": module not found` looks a bit strange for me. I've already checked my machine config patch and rewrote it by hand, reapplied the config and rebooted the node. The error still comes up about every minute and the validation still fails.

Now I have no idea what else I can check or how to solve the issue.

`talosctl version`:
```
Client:
        Tag:         v1.4.6
        SHA:         8615b213
        Built:       
        Go version:  go1.20.5
        OS/Arch:     linux/amd64
Server:
        NODE:        REMOVED
        Tag:         v1.4.6
        SHA:         8615b213
        Built:       
        Go version:  go1.20.5
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```

**Comment by smira** [comment]
I would guess you haven't installed the system extension yet. At the moment system extensions are installed on upgrade/install.

You can trigger installation of the extension by doing an upgrade to the same version of Talos:

```
talosctl upgrade -n <NODE> -i ghcr.io/siderolabs/installer:v1.4.6 --preserve
```

**Comment by alexweidemann** [comment]
Hi @smira ,

you are right. Now it works. I think I missed the line: `In order to update the system extensions for a running instance, update .machine.install.extensions and upgrade Talos. (Note: upgrading to the same version of Talos is fine).` in the documentation. Thank you for your help!

**Comment by walnuss0815** [comment]
Hi @smira ,

you are right. Now it works. I think I missed the line: In order to update the system extensions for a running instance, update .machine.install.extensions and upgrade Talos. (Note: upgrading to the same version of Talos is fine). in the documentation. Thank you for your help!

**Comment by bernardgut** [comment]
Sorry to necro this but I have the same issue on Talos 1.6 and the docs now says that `.machine.install.extensions`, is deprecated. How do we install drbd in the newer versions ?

**Comment by smira** [comment]
@bernardgut https://www.talos.dev/v1.6/talos-guides/install/boot-assets/#image-factory

**Comment by bernardgut** [comment]
Actually never-mind my post. I have found an actual bug where the image loaded (ISO) is getting the extensions of a "previous" image when you do not entirely wipe the node from Omni and re-create it in-between installs. Something about Metadata not being wiped out I would think ? Anyway I will create a separate ticket to discuss

**Comment by bernardgut** [comment]
see https://github.com/siderolabs/omni/issues/139
