### ISSUE TITLE
[feature request] estargz extension

### ISSUE THREAD

**Issue by rsmitty** [siderolabs/extensions#206]
We should take a look at creating an estargz extension for Talos if possible. Customers have a need for this type of image loading and it could have some real value for others pulling big images as well. It feels like an extension might be a nice way to tackle this as opposed to having it baked into talos, since I _think_ that it's just enabling some containerd plugins.

**Comment by frezbo** [comment]
@rsmitty i guess this is done?

**Comment by rsmitty** [comment]
yep, should be good to go.
