### ISSUE TITLE
iscsid failing to load due to missing libraries

### ISSUE THREAD

**Issue by hqnna** [siderolabs/extensions#237]
I noticed my nodes infinitely looping, so i decided to check the logs, it seems `ext-iscsid` is unable to find `libcrypto` for some reason
```
10.10.11.7: Error loading shared library libcrypto.so.3: No such file or directory (needed by /usr/local/sbin/iscsid)
10.10.11.7: Error loading shared library libcrypto.so.3: No such file or directory (needed by /usr/local/lib/libisns.so.0)
```

**Comment by frezbo** [comment]
which version of talos and which version of iscsi-tools extensions is this?

**Comment by hqnna** [comment]
I've tried talos version `1.5.0` and `1.5.3`, and i'm using iscsi-tools version `1.4` which is the latest.

**Comment by frezbo** [comment]
https://ci.dev.talos-systems.io/siderolabs/talos/37274/1/8 it works with 1.5.3, the tests passes, do you have any other extensions?

**Comment by hqnna** [comment]
I have the `qemu-agent` system extension, could it be conflicting with it?

**Comment by frezbo** [comment]
> I have the `qemu-agent` system extension, could it be conflicting with it?

no, it shouldn't, the test runs with all extensions enabled (except nvidia, that;s a different test)

**Comment by frezbo** [comment]
what does `talosctl services` show? Also `talosctl dmesg`

**Comment by hqnna** [comment]
I've shut down the cluster for the night, however if you want to test my setup, `ghcr.io/hqnna/talos:v1.5.0` is my talos installer.

Only other variations was that I had 4 nodes, 1 control plane, 3 workers. each had 2 100GB disks, one for system, one for data mounted at `/var/mnt/data`.

**Comment by frezbo** [comment]
the logs would really help

**Comment by hqnna** [comment]
Alright give me a moment, i'll spin up a node and grab the logs.

**Comment by frezbo** [comment]
i can wait, tomorrow is also fine, have a good night

**Comment by hqnna** [comment]
Here is the requested output(s), services and dmesg in order
```
NODE         SERVICE                STATE     HEALTH   LAST CHANGE   LAST EVENT
10.10.11.7   apid                   Running   OK       55s ago       Health check successful
10.10.11.7   containerd             Running   OK       56s ago       Health check successful
10.10.11.7   cri                    Running   OK       55s ago       Health check successful
10.10.11.7   dashboard              Running   ?        58s ago       Process Process(["/sbin/dashboard"]) started with PID 1713
10.10.11.7   etcd                   Running   OK       23s ago       Health check successful
10.10.11.7   ext-iscsid             Waiting   ?        3s ago        Error running Containerd(ext-iscsid), going to restart forever: task "ext-iscsid" failed: exit code 127
10.10.11.7   ext-qemu-guest-agent   Waiting   ?        54s ago       Waiting for file "/dev/virtio-ports/org.qemu.guest_agent.0" to exist
10.10.11.7   ext-tgtd               Running   ?        55s ago       Started task ext-tgtd (PID 1915) for container ext-tgtd
10.10.11.7   kubelet                Waiting   Fail     0s ago        Error running Containerd(kubelet), going to restart forever: task "kubelet" failed: exit code 1
10.10.11.7   machined               Running   OK       59s ago       Health check successful
10.10.11.7   trustd                 Running   OK       55s ago       Health check successful
10.10.11.7   udevd                  Running   OK       58s ago       Health check successful
```

as well as the [dmesg](https://github.com/siderolabs/extensions/files/12747228/dmesg.txt) logs, as they were too long to paste in.

**Comment by hqnna** [comment]
Good morning, checking the service logs for `ext-iscsid` shows the following:

```
10.10.11.7: 2023/09/28 15:34:36 iscsid-wrapper: starting...
10.10.11.7: 2023/09/28 15:34:36 iscsid-wrapper: completed..., execing into iscsid
10.10.11.7: Error loading shared library libcrypto.so.3: No such file or directory (needed by /usr/local/sbin/iscsid)
10.10.11.7: Error loading shared library libcrypto.so.3: No such file or directory (needed by /usr/local/lib/libisns.so.0)
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: EVP_PKEY_get_size: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: DSA_generate_parameters_ex: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: ERR_reason_error_string: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: EVP_PKEY_get_bits: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: PEM_write_DSAparams: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: EVP_SignFinal: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: ERR_func_error_string: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: PEM_write_PUBKEY: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: i2d_DSA_PUBKEY: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: DSA_new: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: EVP_VerifyFinal: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: EVP_MD_CTX_new: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: EVP_PKEY_free: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: DSA_generate_key: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: EVP_sha1: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: BN_GENCB_new: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: PEM_read_DSAparams: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: EVP_DigestUpdate: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: BN_GENCB_set_old: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: EVP_PKEY_get0_DSA: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: PEM_write_PrivateKey: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: EVP_MD_CTX_free: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: OPENSSL_init_crypto: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: BN_GENCB_free: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: DSA_free: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: PEM_read_PUBKEY: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: EVP_PKEY_new: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: EVP_PKEY_assign: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: d2i_DSA_PUBKEY: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: PEM_read_PrivateKey: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: DSA_get0_key: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: ERR_get_error: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: EVP_PKEY_get_base_id: symbol not found
10.10.11.7: Error relocating /usr/local/lib/libisns.so.0: EVP_DigestInit: symbol not found
10.10.11.7: Error relocating /usr/local/sbin/iscsid: EVP_sha256: symbol not found
10.10.11.7: Error relocating /usr/local/sbin/iscsid: EVP_MD_CTX_new: symbol not found
10.10.11.7: Error relocating /usr/local/sbin/iscsid: EVP_sha1: symbol not found
10.10.11.7: Error relocating /usr/local/sbin/iscsid: EVP_DigestUpdate: symbol not found
10.10.11.7: Error relocating /usr/local/sbin/iscsid: EVP_md5: symbol not found
10.10.11.7: Error relocating /usr/local/sbin/iscsid: EVP_MD_CTX_free: symbol not found
10.10.11.7: Error relocating /usr/local/sbin/iscsid: RAND_bytes: symbol not found
10.10.11.7: Error relocating /usr/local/sbin/iscsid: EVP_DigestInit_ex: symbol not found
10.10.11.7: Error relocating /usr/local/sbin/iscsid: EVP_DigestFinal_ex: symbol not found
```

I build my ISO and installer image with the following:

```sh
podman run --rm -t -v $PWD/images:/out ghcr.io/siderolabs/imager:v1.5.3 iso \      
        --system-extension-image ghcr.io/siderolabs/iscsi-tools:v0.1.4 \
        --system-extension-image ghcr.io/siderolabs/qemu-guest-agent:8.1.1

podman run --rm -t -v $PWD/images:/out ghcr.io/siderolabs/imager:v1.5.3 installer \      
        --system-extension-image ghcr.io/siderolabs/iscsi-tools:v0.1.4 \
        --system-extension-image ghcr.io/siderolabs/qemu-guest-agent:8.1.1
```

I heavily doubt that me using `podman` rather than `docker` is causing issues as it doesn't spit out any errors.

---

I followed the typical node setup procedure I do with the default images:

1. boot Qemu VM with the `talos-1.5.3-amd64.iso` (or a custom built iso)
2. Modify the machine config to point to `/dev/vda` for install, and `/dev/vdb` mounted on `/var/mnt/data`
3. Modify the machine config to use my custom image at `ghcr.io/hqnna/talos:v1.5.3` 
4. Run `talosctl apply-config -i -e 10.10.11.7 -n 10.10.11.7 -f controlplane.yaml`
5. Wait for it to reboot then bootstrap kubernetes with the following:
  a. `talosctl bootstrap -e 10.10.11.7 -n 10.10.11.7 --talosconfig talosconfig`
6. Wait for it to fully bootstrap and show services as `healthy`

Even after all services have fully started and show as healthy `ext-iscsid` boot-loops with exit code `127`.

**Comment by silenium-dev** [comment]
I also have this issue, though it is only occurring on my worker nodes. There are no configuration differences between control-plane and worker nodes, except for networking and the left-out parts for control-plane services (kube-proxy, api-server, cni etc.). Maybe there is some difference between the control-plane and the worker images?

**Comment by hqnna** [comment]
That could be a possibility. Though missing libcrypto / ssl libraries is a very strange difference.

**Comment by silenium-dev** [comment]
Maybe one of control-plane related services ships with it

**Comment by hqnna** [comment]
The logs I posted above are coming from a control-plane is the weird thing.

**Comment by hqnna** [comment]
![image](https://github.com/siderolabs/extensions/assets/46457601/b2c7956b-941b-474c-8871-df0b89a55e9e)

**Comment by silenium-dev** [comment]
Could you share your config? Without the secrets of course

**Comment by hqnna** [comment]
this is a test configuration not an actual cluster setup so i can share the [full configs](https://github.com/siderolabs/extensions/files/12751580/configs.tar.gz).

**Comment by hqnna** [comment]
Alright so looking over both and comparing results:

- I doubt it's the kubernetes version as I had this issue with `v1.28.2` as well
- I'll give the official image a try with extensions enabled in the `install` section
  - It should be [noted](https://www.talos.dev/v1.5/talos-guides/configuration/system-extensions/) that this way is deprecated according to the Talos documentation
- Maybe it has something to do with the lack of `gvisor`? I doubt it, but it's possible.
- Maybe some config parameters are affecting this, though I'm using stock generally.
- I doubt network configuration could affect this, but I could be wrong.

Given these evaluations I'm guessing it's either:

- The fact a custom image is being used rather than the official with extensions in the config
- The lack of gvisor somehow preventing libcrypto from existing somehow maybe
- Maybe somehow some configuration parameters are not allowing it to work

**Comment by hqnna** [comment]
> Alright so looking over both and comparing results:
> 
> * I doubt it's the kubernetes version as I had this issue with `v1.28.2` as well
> * I'll give the official image a try with extensions enabled in the `install` section
>   
>   * It should be [noted](https://www.talos.dev/v1.5/talos-guides/configuration/system-extensions/) that this way is deprecated according to the Talos documentation
> * Maybe it has something to do with the lack of `gvisor`? I doubt it, but it's possible.
> * Maybe some config parameters are affecting this, though I'm using stock generally.
> * I doubt network configuration could affect this, but I could be wrong.
> 
> Given these evaluations I'm guessing it's either:
> 
> * The fact a custom image is being used rather than the official with extensions in the config
> * The lack of gvisor somehow preventing libcrypto from existing somehow maybe
> * Maybe somehow some configuration parameters are not allowing it to work

Though the documentation also says this:

```
Depending on the nature of the system extension (e.g. network device driver or containerd plugin), it may be necessary to include the extension in both initial boot assets and disk images/installer, or just the installer.
```

So *maybe* it has to be in the `.install.extensions` section regardless? I'll have to give that a try.

**Comment by silenium-dev** [comment]
OpenSSL is available when this error occurs, but with version 1.1.x, not 3.x

```
# talosctl -n 10.0.0.22 list /usr/lib
...
10.0.0.22   libcrypto.so
10.0.0.22   libcrypto.so.1.1
```

**Comment by hqnna** [comment]
Alright so tested a few things to try to slim down the positibilies:

- Changing the kubernetes version from `1.26.9` to `1.28.2` did not fix it
- Changing the extensions from a custom image to `.install.extensions` did not fix it
- Removing the secondary disk to see if the mount is causing it did not fix it
- Using the official talos v1.5.3 installation ISO image

Leaving the only possible options as:

- Some configuration option somehow preventing it from working
- Somehow network configuration preventing it from loading
- Not having gvisor enabled not allowing it to work

But i don't see how either of those would effect the version of openssl installed

**Comment by hqnna** [comment]
I'm wondering.. could it be the `serverTLSBootstrap: true` option you have in your config?

**Comment by silenium-dev** [comment]
I've just checked my control-planes, and they don't have OpenSSL 3.x either.

**Comment by hqnna** [comment]
alright so my friend recommended downgrading to `iscsi-tools:v0.1.1` and the error went away, it seems `v0.1.4` is broken.

**Comment by frezbo** [comment]
I cannot reproduce this with Talos `1.5.3`. Used the [boot assets](https://www.talos.dev/v1.5/talos-guides/install/boot-assets/) to generate an installer with iscsid installed and it all works fine

**Comment by frezbo** [comment]
> ~I cannot reproduce this with Talos `1.5.3`. Used the [boot assets](https://www.talos.dev/v1.5/talos-guides/install/boot-assets/) to generate an installer with iscsid installed and it all works fine~

My mistake, used a wrong installer, I can reproduce the issue locally

**Comment by smira** [comment]
Please use this pinned version for Talos 1.5.3: `ghcr.io/siderolabs/iscsi-tools:v0.1.4@sha256:3ab305068aa28513b26ab3c5b1f2937dbe3f63b9c50abe290287cc58eb454bb9`

**Comment by linuxmaniac** [comment]
hit by this one today. Pinned version fixed the issue.

**Comment by mdeterman** [comment]
Thanks, This only burned a day running down this issue.

**Comment by lucasmaurice** [comment]
If someone else experiment the issue, I have it running my nodes on vmware.

The solution mentioned by @smira works for me:

First build and push my custom image running this:

```bash
docker run --rm -t -v $PWD/_out:/out ghcr.io/siderolabs/imager:v1.5.4 installer --arch amd64 --system-extension-image ghcr.io/siderolabs/iscsi-tools:v0.1.4@sha256:58cbadb0a315d83e04b240de72c5ac584e9c63b690b2c4fcd629dd1566c3a7a1
crane push _out/metal-amd64-installer.tar <my-registry>/talos-installer:v1.5.4
```

Then running the upgrade on the nodes using my custom image:

```bash
talosctl --nodes n1,n2,n3 upgrade --image <my-registry>/talos-installer:v1.5.4
```

BEFORE:

```text
NODE   SERVICE      STATE     HEALTH   LAST CHANGE   LAST EVENT
n1     apid         Running   OK       2h2m54s ago   Health check successful
n1     containerd   Running   OK       2h2m55s ago   Health check successful
n1     cri          Running   OK       2h2m53s ago   Health check successful
n1     dashboard    Running   ?        2h3m1s ago    Process Process(["/sbin/dashboard"]) started with PID 2139
n1     ext-iscsid   Waiting   ?        3s ago        Error running Containerd(ext-iscsid), going to restart forever: task "ext-iscsid" failed: exit code 127
n1     ext-tgtd     Running   ?        2h2m53s ago   Started task ext-tgtd (PID 2299) for container ext-tgtd
n1     kubelet      Running   OK       2h2m51s ago   Health check successful
n1     machined     Running   OK       2h3m3s ago    Health check successful
n1     udevd        Running   OK       2h3m1s ago    Health check successful
```

AFTER:

```text
NODE   SERVICE      STATE     HEALTH   LAST CHANGE   LAST EVENT
n1     apid         Running   OK       1m5s ago      Health check successful
n1     containerd   Running   OK       1m6s ago      Health check successful
n1     cri          Running   OK       1m4s ago      Health check successful
n1     dashboard    Running   ?        1m8s ago      Process Process(["/sbin/dashboard"]) started with PID 2136
n1     ext-iscsid   Running   ?        1m4s ago      Started task ext-iscsid (PID 2335) for container ext-iscsid
n1     ext-tgtd     Running   ?        1m4s ago      Started task ext-tgtd (PID 2292) for container ext-tgtd
n1     kubelet      Running   OK       44s ago       Health check successful
n1     machined     Running   OK       1m11s ago     Health check successful
n1     udevd        Running   OK       1m8s ago      Health check successful
```

It works on all the nodes:

```text
talosctl --nodes n1,n2,n3 services | grep ext-iscsid
n1   ext-iscsid   Running   ?        4m51s ago     Started task ext-iscsid (PID 2286) for container ext-iscsid
n2   ext-iscsid   Running   ?        3m45s ago     Started task ext-iscsid (PID 2341) for container ext-iscsid
n3   ext-iscsid   Running   ?        4m43s ago     Started task ext-iscsid (PID 2288) for container ext-iscsid
```
