### ISSUE TITLE
add support for kata container runtime

### ISSUE THREAD

**Issue by smira** [siderolabs/extensions#24]
See https://github.com/kata-containers/kata-containers/blob/main/docs/install/container-manager/containerd/containerd-install.md

Currently blocked on https://github.com/kata-containers/kata-containers/issues/927, as Talos is only cgroups v2.

**Comment by paulwollgast** [comment]
+1 on this one, would be great to see!

**Comment by stevefan1999-personal** [comment]
Kata containers binaries can be obtained from https://github.com/kata-containers/kata-containers/releases with the kata-static package (like https://github.com/kata-containers/kata-containers/releases/download/3.1.3/kata-static-3.1.3-x86_64.tar.xz),

Caution: This whole package is 2GB in size and would probably make the final SquashFS image large in size.

Another problem is that you can actually change the config of Kata Container (by default the path is /opt/kata/share/defaults/kata-containers/). Maybe we need to find somewhere to store those mutable config

**Comment by frezbo** [comment]
kata containers are now available as an extension
