### ISSUE TITLE
Error when installing iscsi-tools

### ISSUE THREAD

**Issue by tipok** [siderolabs/extensions#258]
I'm probably doing something wrong and would appreciate any help.
I'm running talos v1.5.4 on metal and trying to install ghcr.io/siderolabs/iscsi-tools:v0.1.4@sha256:180f0d17015ecd1c02c0f0f421aa9c5410970f33cd61bf43b1bc4c52e9310e69
Unfortunately getting this error
```log
: user: warning: [2023-11-03T21:25:57.437836397Z]: Error: error validating extension "iscsi-tools": path "/usr/include/libopeniscsiusr.h" is not allowed in extensions
``` 

Any idea?

**Comment by frezbo** [comment]
Seems using a wrong version of iscsi tools as per docs https://github.com/siderolabs/extensions?tab=readme-ov-file#installing-extensions

```bash
❯ crane export ghcr.io/siderolabs/extensions:v1.5.4 | tar x -O image-digests | grep iscsi
ghcr.io/siderolabs/iscsi-tools:v0.1.4@sha256:58cbadb0a315d83e04b240de72c5ac584e9c63b690b2c4fcd629dd1566c3a7a1
```

**Comment by tipok** [comment]
Yes, this worked, thank you.
I've tried to run `crane`, but could not because of a denied error.
Anyway, thank you for the fast help
