### ISSUE TITLE
What is i915-ucode

### ISSUE THREAD

**Issue by rouke-broersma** [siderolabs/extensions#263]
The PR that introduced this makes it seem like this is the intel graphics driver for the igpu, however it's listed under firmware and not drivers. Is this required to use the igpu in pods running on talos or does this update the actual microcode for the igpu? It's unclear and there's no mention anywhere about what most packages in this repo do.

**Comment by smira** [comment]
It's microcode for `i915` family of graphics cards. It doesn't enable more than that itself.

**Comment by rouke-broersma** [comment]
@smira could you please clarify a bit further? I don't understand the distinction. When would I use the extension?

**Comment by smira** [comment]
When you need to load firmware into your `i915`. If you need to load it, you should know that you need that ;)

https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915

**Comment by rouke-broersma** [comment]
Okay thanks! The reason mm asking is because I want to enable igpu transcoding in plex and the pr that introduced the extension mentions the same for jellyfin. But nice that I don't need it then!
