### ISSUE TITLE
[qemu-guest-agent] Not launching in maintenance mode (1.6.1)

### ISSUE THREAD

**Issue by mlinares1998** [siderolabs/extensions#293]
I'm trying to automate Talos deployments via Terraform on my Proxmox cluster.
To be able to provision the VM's correctly QEMU GA has to be started on boot so the Terraform Proxmox provider can get the VM's IP addresses.

This seems possible now since v1.6.0 using early extension initialization feature on maintenance mode. 
Unfortunately QEMU GA seems to not be working unlike Xen GA. It get's stuck on "Waiting for service "cri" to be registered" message.

![image](https://github.com/siderolabs/extensions/assets/15200008/88ac7a3b-4484-429a-994f-df279d5f362c)

I'm using an ISO bundled with QEMU GA by Image Factory with the following configuration.

```
Your image schematic ID is: f4524a31eb3f0cf8dc1449b8f43755d5ae4d35fc5c5b27eb79c8b8aca590bdfa
customization:
    systemExtensions:
        officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/intel-ucode
            - siderolabs/qemu-guest-agent
```

QEMU GA is correctly listed by talosctl

```
❯ talosctl -n 10.120.0.35 get extensions -i
NODE   NAMESPACE   TYPE              ID   VERSION   NAME               VERSION
       runtime     ExtensionStatus   0    1         amd-ucode          20231111
       runtime     ExtensionStatus   1    1         intel-ucode        20231114
       runtime     ExtensionStatus   2    1         qemu-guest-agent   8.1.3
       runtime     ExtensionStatus   3    1         schematic          f4524a31eb3f0cf8dc1449b8f43755d5ae4d35fc5c5b27eb79c8b8aca590bdfa
```

Thanks!

**Comment by frezbo** [comment]
This is due to this https://github.com/siderolabs/extensions/blob/main/guest-agents/qemu-guest-agent/qemu-guest-agent.yaml#L23-L29

maybe we can move this to `/system/run` which is available in maintenance mode, the caveat being it gets blown away on next boot since it's ephemeral, but I guess it doesn't need to persist anything

**Comment by mlinares1998** [comment]
Hi @frezbo. Thanks for your time!
I have tested building the extension locally with your suggestion, then adding it to an iso by Imager but got no avail.
It still gets stuck waiting for "cri" service.
![image](https://github.com/siderolabs/extensions/assets/15200008/8dc77dae-0f4e-4a11-854e-3f5e692227ec)

Tried rebuilding it removing the cri requirement (Line 3) and the extension gets into a restart loop.
![image](https://github.com/siderolabs/extensions/assets/15200008/f36b8b79-5ab5-4f5a-a6fc-ef3cf8a43267)

**Comment by frezbo** [comment]
I'll check this, yes the `cri` dependency needs to be removed (it's a way for waiting for `/var` to be mounted)

**Comment by mlinares1998** [comment]
Hi @frezbo 
Did another test and managed to get it working!

Removed the cri service requirement and bound /system/run to /var/run as destination instead in[ L23.](https://github.com/siderolabs/extensions/blob/main/guest-agents/qemu-guest-agent/qemu-guest-agent.yaml#L23)

![image](https://github.com/siderolabs/extensions/assets/15200008/774a8650-5d3c-459b-93bb-9e4754a59718)
![image](https://github.com/siderolabs/extensions/assets/15200008/886f394b-ae9c-4549-b07f-e1cf1015afc2)
```

NODE   NAMESPACE   TYPE      ID                     VERSION   RUNNING   HEALTHY   HEALTH UNKNOWN
       runtime     Service   containerd             3         true      true      false
       runtime     Service   dashboard              1         true      false     true
       runtime     Service   ext-qemu-guest-agent   1         true      false     true
       runtime     Service   machined               2         true      true      false
       runtime     Service   udevd                  2         true      true      false
```

**Comment by frezbo** [comment]
Awesome, would you mind creating a PR?

**Comment by frezbo** [comment]
> Removed the cri service requirement and bound /system/run to /var/run as destination instead in[ L23.](https://github.com/siderolabs/extensions/blob/main/guest-agents/qemu-guest-agent/qemu-guest-agent.yaml#L23)

I would probably say use `/system/run/qemu-guest-agent` to `/var/run`

**Comment by mlinares1998** [comment]
> > Removed the cri service requirement and bound /system/run to /var/run as destination instead in[ L23.](https://github.com/siderolabs/extensions/blob/main/guest-agents/qemu-guest-agent/qemu-guest-agent.yaml#L23)
> 
> I would probably say use `/system/run/qemu-guest-agent` to `/var/run`

Let me test it.

**Comment by mlinares1998** [comment]
> Awesome, would you mind creating a PR?

PR created.
