### ISSUE TITLE
An extension for Video4Linux

### ISSUE THREAD

**Issue by USA-RedDragon** [siderolabs/extensions#295]
I have a usecase in which I need V4L modules in the kernel. I am using `ffmpeg` with a USB webcam attached to a nearby 3D printer and want to run an `ffmpeg` transcoding job from the webcam to both an Obico instance and an `nginx-rtmp` instance for detecting print failures and accessing the stream remotely, respectively.

Given this is pretty niche, would Siderolabs accept a PR for a new extension for V4L similar to what is done for a few other kernel modules?

**Comment by frezbo** [comment]
yes, adding this as an extension is fine, go for it
