### ISSUE TITLE
Publish the wasmedge extension with a tagged version

### ISSUE THREAD

**Issue by rgl** [siderolabs/extensions#318]
The [wasmedge extension](https://github.com/siderolabs/extensions/pkgs/container/wasmedge) introduced at https://github.com/siderolabs/extensions/pull/305 failed the publication.

Can you please fix it, so we can use a tagged version?

Also please note, not sure if its been fixed already, but listing the extensions, shows some inconsistencies between the used tags (one has the `v` prefix, the other does not):

```console
$ talosctl -n $c0 get extensions
NODE         NAMESPACE   TYPE              ID   VERSION   NAME               VERSION
10.17.3.10   runtime     ExtensionStatus   0    1         qemu-guest-agent   8.1.3
10.17.3.10   runtime     ExtensionStatus   1    1         wasmedge           v0.3.0
```

**Comment by frezbo** [comment]
The `v` comes from upstream, we follow whatever upstream does. wasmedge will only be available for 1.7+
