### ISSUE TITLE
qemu-guest-agent not running shortly after startup.

### ISSUE THREAD

**Issue by sre42** [siderolabs/extensions#338]
Im using the 1.6.6 talos build with qemu-guest additions from the Image factory.

I am creating VMs via terraform on my Proxmox cluster and am also bootstrapping them via the talos terraform provider.

The module is able to correctly obtain the IP address and the UI also shows the IP correctly but then shortly after reports that the agent is not running shortly after.

Terraform then hangs during plan/apply with the following error: check ip result error 500 QEMU guest agent is not running

I am able to console into the VMs but its hard for me to scroll up enough to access the error logs.

Any recommended ways I could debug this?

Thanks,

**Comment by frezbo** [comment]
After the config is applied, talos gets installed and reboots, it's probably that
