### ISSUE TITLE
DRBD >= 9.2.7

### ISSUE THREAD

**Issue by Ulrar** [siderolabs/extensions#340]
Hi,

I'm using the DRBD 9.2.6 extension for Talos 1.6.6, but for some reason pretty much all actions are blocked because of "pool mixing" between 9.2.6 and 9.2.7, even though there's no mixing going on (see https://github.com/piraeusdatastore/piraeus-operator/issues/626).

I realize that's likely unrelated to Talos, but any chance we could get a 9.2.7 or 9.2.8 extension published ?
Thanks

**Comment by frezbo** [comment]
DRBD doesn't now built with Talos kernel, so unless upstream is fixed, there's won't be drbd release for 1.7

**Comment by Ulrar** [comment]
That's all kinds of worrying, since my understanding is 1.7 won't yet support unmanaged partitions to allow to migrate to something else. Is there any alternatives to linstor that Talos supports and don't require dedicated separate disks ?

Regardless, what I was hoping for here is an update for 1.6.6 stable

**Comment by smira** [comment]
We could backport newer DRBD to 1.6 though

**Comment by smira** [comment]
@Ulrar  if you could attract some attention to the issue https://github.com/LINBIT/drbd/issues/84, we can get DRBD in 1.7 with Linux 6.6

**Comment by WanzenBug** [comment]
> DRBD doesn't now built with Talos kernel

What exactly is the issue? Latest DRBD release should include compatibility up to Linux 6.7.

**Comment by frezbo** [comment]
> > DRBD doesn't now built with Talos kernel
> 
> What exactly is the issue? Latest DRBD release should include compatibility up to Linux 6.7.

The spatch server doesn't  seem to provide patches

**Comment by WanzenBug** [comment]
Strange, is it not reachable, or producing errors?

Sorry, I'm not familiar with the way the talos linux builds work: is networking even enabled?
