### ISSUE TITLE
What extensions are included by default in https://factory.talos.dev/? 

### ISSUE THREAD

**Issue by evanrich** [siderolabs/extensions#356]
This might not be the best place to ask, but I was turned on to https://factory.talos.dev/ for producing a custom image (I'm trying to add support for binfmt-misc).   on that site, there's a bunch of system extensions listed, but it got me wondering if my existing talos install already had some enabled.  Is there either a way to find out whats currently enabled, or know if the factory site already matches the default install (and anything extra I add is indeed just extra extensions?)  Thanks!

Also, say I'm running talos on a box with an intel processor, is there any benefit to me loading say, the `intel-ucode` extension for microcode updates?   the docs aren't super helpful on what all of these are for.

Edit: it looks like ```$ talosctl get extensions``` shows no currently installed extensions.

**Comment by smira** [comment]
`talosctl get extensions` shows list of extensions, and if produced via Image Factory, there will be a virtual extension with your schematic ID.
