### ISSUE TITLE
Extensions docs need some help

### ISSUE THREAD

**Issue by kingdonb** [siderolabs/extensions#363]
Admit this is a beta feature that was just introduced, so some of this is probably already known.

https://github.com/siderolabs/extensions?tab=readme-ov-file#installing-extensions
https://github.com/siderolabs/extensions/blob/main/network/tailscale/README.md#subnet-routing
https://github.com/siderolabs/extensions/blob/main/network/tailscale/README.md#usage

I've only installed 3 extensions so far. I used the Image Factory, which none of these docs suggested or recommended, and it seems to be the best supported way to bundle extensions for your Talos image. That aside... after reading all of these, I was left with the impression that what I should do is put that ExtensionServiceConfig into a myconfig.yaml file and apply it with `talosctl apply -n controlplaneip -f myconfig` -- what seems to have worked, instead, is to append it to the `controlplane.yaml` instead, then do `apply` and `upgrade` on the resulting controlplane.yaml+myconfig.yaml.

Sort of. That almost worked, but the Talos node I wound up with no longer had any of my extensions installed. I ran the upgrade again with --image (specified repeating the same value as what `install.image` config I had mentioned in the `controlplane.yaml` file) - I think I probably do need to go back and read more upgrade docs, but maybe there's some thing that could be improved about this workflow. I am running single-node mode, this is not a HA or production cluster.

Still not sure if that was the correct procedure but I found `talosctl get extensionserviceconfig` seems to reveal the config applied successfully where I expected to find it (and I'm able to get into my tailscale tailnet service network via subnet router, so I guess it worked!) It seemed like this stuff all worked yesterday too, but today I came back after upgrading with `--image` and found it had rolled everything back to 1.6.5, maybe a problem of having mismatched CLI. (Did I mention I'm new here)

Is there a Talos for Beginners docs where I should start reading again, or similar docs where any of this stuff is covered in dead simple terms laid out flat for newbies, or is ExtensionServiceConfig still too new to expect that kind of hand-holding in documentation about how to use it (this feature seems to have been released in beta only days ago, in the very tip beta release which I am using now 🎉 )

Anyway, I bring this up, because running `talosctl apply myconfig.yaml` emitted some kind of message about applying config without rebooting, and I was left stranded with basically no idea that I should run `talosctl upgrade` now. I'm still not sure how I figured that out. At some point I think my node rebooted itself, went into some kind of failure state, and I was able to recover it in maintenance mode. I don't think that was supposed to happen. I guess there might be more than one way to load an ExtensionServiceConfig into the cluster, I heard about some kind of Talos-Kubernetes API bridge configuration where you can add Talos config directly through the Kubernetes API. I guess that's a secondary method, and `talosctl apply` is the main way to do it.

But through misusing `talosctl apply` in straightforward ways that seemed to be only doing exactly just what the docs suggested I should do, I was able to unfortunately take down my cluster and put the control plane into unauthenticated/maintenance mode, so maybe some additional guard rails are in order.

I would help with this but I'm not sure where to begin, just wanted to report on my findings and open to learn and review docs, (and maybe help someone else find their way through the maze in case they tripped over all the same things I did...)

**Comment by kingdonb** [comment]
To be a bit more specific, reading here:

> Create a config document as described in the tailscale [README](https://github.com/siderolabs/extensions/blob/main/network/tailscale/README.md#usage) and apply the patch.

in the Upgrading Talos guide:

https://www.talos.dev/v1.7/talos-guides/upgrading-talos/

The README doesn't really go into detail about how to apply the patch.

```
> talosctl apply -n node myconfig.yaml
> talosctl upgrade -n node
```

This is where I figured out that "upgrade" comes after "apply". The apply command didn't actually work, without `-f`. Putting the ExtensionServiceConfig into `myconfig.yaml` and passing it to `apply -f` was the step that apparently took down the entire control plane and left me in maintenance mode, needing me to execute a manual recovery in `--insecure` mode.

**Comment by smira** [comment]
There are many missing pieces of the documentation, so we would appreciate any updates as PRs, if there's something missing, we can update/fix it up.

**Comment by kingdonb** [comment]
The main thing missing is an actual walkthrough of how to install an extension. I found a few references to this:

https://github.com/siderolabs/extensions?tab=readme-ov-file#installing-extensions

where I would expect to see the steps laid out how to install an extension, but instead it explains only how to "find a container reference" - which I guess I'd use in the install part of the worker node / talos control plane config, only I've read in a few places that method is deprecated. I guess this stuff is pretty hot-off-the-presses new and some of these things may still be in flux.

I am a newbie and I wouldn't want to mislead people! (but if I submit a PR and it's wrong, you can tell me so, and I'll fix it 👍)

Thanks for the response

**Comment by smira** [comment]
Some basics are here: https://www.talos.dev/v1.6/talos-guides/install/boot-assets/#image-factory

But I don't think we have a document explaining extensions which require configuration.
