### ISSUE TITLE
gVisor fails with cgroups support on Talos

### ISSUE THREAD

**Issue by smira** [siderolabs/extensions#4]
Error message:

```
172.20.0.2: {"error":"failed to create containerd task: failed to create shim task: OCI runtime create failed: creating container: Rel: can't make podruntime/runtime relative to /: unknown","level":"error","msg":"RunPodSandbox for \u0026PodSandboxMetadata{Name:nginx-gvisor,Uid:540e0e84-7090-48e9-838b-8d7d0965e301,Namespace:default,Attempt:0,} failed, error","time":"2022-01-25T14:24:32.902977189Z"}
```

It seems to be related to the cgroups handling code, as `podruntime/runtime` is the cgroup of the `cri` process.

I traced the error back to: https://github.com/google/gvisor/blob/fa4e2fff8a842dcfe6518d8bf9cdbd94750780cc/runsc/cgroup/cgroup.go#L292

**Comment by frezbo** [comment]
@smira I guess this can be closed now?

**Comment by smira** [comment]
I believe it's still a problem. This is something in gvisor and we disable cgroups support via config
