### ISSUE TITLE
`tailscale` versions pinned for a given Talos version are quickly out of date and have security vulnerabilities

### ISSUE THREAD

**Issue by michaelbeaumont** [siderolabs/extensions#402]
The extension has been updated to v1.64.2 in this repo but I still only have the option of v1.62.1 for Talos v1.7.4

I suppose solving this would mean either:
* updating the extension versions for already released Talos versions
* allowing users to specify an image version in the factory schematic

**Comment by smira** [comment]
updating tailscale extension version is doable, you can either open a request for it (e.g. tailscale x.y.z has this CVE, please update in `release-1.7`), or do a PR yourself.

when using Image Factory, every build is reproducible, so the extension versions are fixed for a given release of Talos, but you can use manual way via the `imager` container to build your own versions as well
