### ISSUE TITLE
change the vmtoolsd extension name directory too?

### ISSUE THREAD

**Issue by rgl** [siderolabs/extensions#403]
I've noticed the name change of vmtoolsd extension  at https://github.com/siderolabs/extensions/commit/eb36dc50c3abe9119eb0f31a52959df1f14876ac, but it seems things are half-done.

The description at https://github.com/siderolabs/extensions/pkgs/container/vmtoolsd-guest-agent#guest-agents is now somewhat odd, as it contains:

[talos-vmtoolsd](https://github.com/siderolabs/extensions/blob/main/guest-agents/talos-vmtoolsd)	[ghcr.io/siderolabs/talos-vmtoolsd](https://github.com/siderolabs/talos-extensions/pkgs/container/talos-vmtoolsd)	[talos-vmtoolsd](https://github.com/siderolabs/talos-vmtoolsd)	upstream version

that is, is named `talos-vmtoolsd` instead of `vmtoolsd-guest-agent`.

that might be related to the directory name at https://github.com/siderolabs/extensions/tree/v1.8.0-alpha.0/guest-agents/talos-vmtoolsd, which also seems to require a rename.

also, we have to use `talosctl -n $c0 service ext-talos-vmtoolsd status` instead of `talosctl -n $c0 service ext-vmtoolsd-guest-agent status`.

I think those should be fixed somehow, to prevent further confusion.

**Comment by frezbo** [comment]
Yes, this was missed and would be ideal, would you mind a PR?

**Comment by rgl** [comment]
@frezbo, not really sure if https://github.com/siderolabs/extensions/pull/407 is enough. please review.
