### ISSUE TITLE
Kata Pods fail to boot with RuntimeClass on Raspberry Pi

### ISSUE THREAD

**Issue by BobyMCbobs** [siderolabs/extensions#404]
### Description

On a Raspberry Pi, with the kata-containers extension, an error is presented instead of a running Pod.

### Logs

```
$ kubectl describe pod failing
...
Events:
...      Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: error: 500  reason: ApiError(VmBoot(DeviceManager(CreateInterruptController(CreateGic(CreateVgic(Vgic error CreateGic(CreateDevice(No such device (os error 19))))))))): unknown
```

### Environment

- Talos version: v1.7.4
- Kubernetes version: v1.30.1
- Customization:
```
customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/kata-containers
```

instructions as per https://github.com/siderolabs/extensions/tree/main/container-runtime/kata-containers

**Comment by BobyMCbobs** [comment]
comms: https://katacontainers.slack.com/archives/C86U7NZND/p1717800942429419

**Comment by BobyMCbobs** [comment]
opened a ticket for cloud-hypervisor on this issue too
https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6524

**Comment by smira** [comment]
Can you please add some context here? Talos extensions just re-package Kata contianers, so might be that something is missing in the Linux kernel?

**Comment by frezbo** [comment]
Closing since it's a hardware lack on support as per https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6524

**Comment by BobyMCbobs** [comment]
That's reasonable. Gotta find the appropriate hardware for it.
