### ISSUE TITLE
Update NVIDIA drivers up to version 550.x

### ISSUE THREAD

**Issue by maxpain** [siderolabs/extensions#406]
Hello.

Current NVIDIA drivers in Talos are quite outdated. 535.129.03 version has been released six months ago.
This version has CUDA 12.2, which is a problem for some new software, such as ffmpeg v7.

Is there any ETA for upgrading it to the latest 550.x branch?

**Comment by smira** [comment]
There is no ETA at the moment, but update will happen at some point before the next Talos release.

**Comment by frezbo** [comment]
Also updating to latest nvidia seems to break enterprise users, so we follow caution in updating nvidia drivers

**Comment by smira** [comment]
> Also updating to latest nvidia seems to break enterprise users, so we follow caution in updating nvidia drivers

I think with this update we should also support older drivers (need to figure out extension names vs. Talos upgrades), but basically provide both 535 and 550 for Talos 1.8.

**Comment by maxpain** [comment]
Theoretically, can we add some option to choose the extension version in factory.talos.dev?

**Comment by smira** [comment]
No, you can use imager if you want your own custom image. And for NVIDIA it's anyways locked to the kernel build, so it won't work for a different version of Talos

**Comment by daper** [comment]
If you get any hot build, I can test it... I would love to have an updated version. I've tried to play with the *imager* and some modules from [here](https://github.com/siderolabs/pkgs/pkgs/container/nonfree-kmod-nvidia-production-pkg) taking the same kernel version from nightlies, but it didn't boot up :(

**Comment by jfroy** [comment]
I have a workflow to build the kernel and the Nvidia open kernel modules [here](https://github.com/jfroy/talos-boot-assets), if you need inspiration. I'm running 6.10.3 with NVIDIA 550.107.02 on my nodes.

**Comment by frezbo** [comment]
Starting Talos 1.8, both LTS and Production NVIDIA versions will be shipped as per support matrix: https://www.talos.dev/v1.8/introduction/support-matrix/
