### ISSUE TITLE
Tailscale TS_ROUTES containing ipv6

### ISSUE THREAD

**Issue by mentos1386** [siderolabs/extensions#432]
Hey all, I have tried to expose ipv6 subnet using `TS_ROUTES` for tailscale extension, but i got the following error in the logs.

```
IP: boot: 2024/07/22 20:01:14 Failed to enable IP forwarding: enabling "/proc/sys/net/ipv6/conf/all/forwarding": open /proc/sys/net/ipv6/conf/all/forwarding: read-only file system
IP: boot: 2024/07/22 20:01:14 To run tailscale as a proxy or router container, IP forwarding must be enabled.
IP: boot: 2024/07/22 20:01:14 You can fix this by running the container with privileged=true, or the equivalent in your container runtime that permits access to sysctls.
```

Should the ipv6 forwarding be enabled by default? Is that already the case for ipv4?

**Comment by smira** [comment]
Enable the related sysctls using [Talos machine configuration](https://www.talos.dev/v1.7/reference/configuration/v1alpha1/config/#Config.machine):

```yaml
machine:
  sysctls:
   net.ipv6.conf.all.forwarding: "1"
```

**Comment by mentos1386** [comment]
Thanks for the fast response @smira, that should fix it.
