### ISSUE TITLE
Request: Add cni-plugins extensions

### ISSUE THREAD

**Issue by vaskozl** [siderolabs/extensions#448]
In https://github.com/siderolabs/talos/issues/6729 it was decided that cni-plugins shouldn't be included by default so as to not bloat the main image.

Talos uses `ghcr.io/siderolabs/install-cni` by default to copy in the plugins on boot, but this is slower than having them pre-installed. This works well.

The advantage is that then the upstream flannel and kube-router helm charts/manifests can be used which allows more fine-grained config over things (e.g. nftables mode, kube-network-policies, etc). Furthemor, it would help boot times as the image pull (after a /var wipe like in an upgrade) and [copy in the initContainer](https://github.com/siderolabs/extras/blob/main/install-cni/scripts/install-cni.sh) could be skipped.

The official way is not super straight forward: https://github.com/siderolabs/talos/discussions/7583 as it requires patching.

Now that the factory is live it would be more elegant to provide the plugins as an option.

**Comment by smira** [comment]
The problem with CNI plugins is that they should be writeable (as many CNIs drop their own plugins there). So the benefit of bundling CNI plugins as a system extension is not what it should be -  delivered as part of Talos Linux image and verified to be same.

So the same effect might be achieved by simply putting a mirror registry in front of the `install-cni` image.

**Comment by vaskozl** [comment]
I think being able to use the flannel and kube-router charts without patches would still be a big usability win. Not all CNIs behave aggressively like Calico and Cilium.

**Comment by smira** [comment]
Yes, that's true as well. So let's keep this open for additional consideration. We could bundle CNI plugins with base Talos as well, as they are always needed (there's no question they won't be needed with almost any CNI).
