### ISSUE TITLE
[ZFS] mount does not shown in talosctl

### ISSUE THREAD

**Issue by tzabbi** [siderolabs/extensions#539]
I updated to the latest talos version (v1.8.3) and kubernetes version (v1.31.3) and using the zfs extension. But unfortunatly the mount isn't shown with the command `talosctl get discoveredvolumes`.

```bash
talosctl get discoveredvolumes | grep

```

In the container the zfs pool is online and healthy

![image](https://github.com/user-attachments/assets/10ea4ced-80cf-418f-ba72-f6bcd19ffa5a)
![image](https://github.com/user-attachments/assets/13c8d2d8-2dfa-4a5c-84d9-2036c11f2c0f)

Can someone help me to solve this issue? I used the guide in the zfs extension page.

**Comment by tzabbi** [comment]
Okay sorry for missing the information. As in the documentation i thought that the zfs raid is shown with the mountpoint like described in the documentation. I will make more research if that is the case with another Talos version. If not I will update the documenation and close the issue.

**Comment by smira** [comment]
The volumes are blockdevices in general - raw disks, partitions, device mapper devices, etc. certainly not mount points

**Comment by frezbo** [comment]
I think it shows up in discovered volumes after a reboot, the block backing the zpool as type zfs

**Comment by tzabbi** [comment]
I learned that zfs by default doesn't creste a block device so it should be fine.
