### ISSUE TITLE
Nvidia cloud native stack fails to start with new nvidia open gpu kernel modules

### ISSUE THREAD

**Issue by tmojzes** [siderolabs/extensions#544]
Since the new version of the nvidia open gpu kernel modules which differentiates between [production](https://github.com/siderolabs/extensions/pkgs/container/nvidia-open-gpu-kernel-modules-production) and [lts](https://github.com/siderolabs/extensions/pkgs/container/nvidia-open-gpu-kernel-modules-lts) versions, the Nvidia related so files are moved to /usr/local/glibc/lib 
![image](https://github.com/user-attachments/assets/2c3ae8ef-4ce8-4df7-bda0-417549842cf3)
from /usr/local/lib in the [previous versions.](https://github.com/siderolabs/extensions/pkgs/container/nvidia-open-gpu-kernel-modules)
![image](https://github.com/user-attachments/assets/b8319460-bc73-4401-be52-635c31dee57d)

Some of these are e.g.: libnvidia-ml.so required for the Nvidia cloud native stack components like [Nvidia Device Plugin](https://github.com/NVIDIA/k8s-device-plugin) and [DCGM exporter](https://github.com/NVIDIA/dcgm-exporter). Both of these loads the before mentioned shared object at runtime and without it they fail to start. The load of the object files is done by the [go-nvml](https://github.com/NVIDIA/go-nvml) library which as far as I know only looks for these files under /usr/local/bin so either it should be modified or the .so files needs to be moved back to their original place.

**Comment by smira** [comment]
Can you give us a minimal reproducer of the problem please? E.g. you `kubectl apply` this, and it fails to run.

**Comment by frezbo** [comment]
@tmojzes are you sure the pod was ran with `runtimeClassName` set?

The dgcm pod seems to run fine in testing

**Comment by frezbo** [comment]
I can get the same error if `runtimeClassName` is not set
