### ISSUE TITLE
Missing build: NUT client extension not built

### ISSUE THREAD

**Issue by mdallaire** [siderolabs/extensions#74]
It seems that an error occured during the nut client extension build.

https://ci.dev.talos-systems.io/siderolabs/extensions/258/1/2

**Comment by frezbo** [comment]
> It seems that an error occured during the nut client extension build.

that should be fine, it got build later on in the commits. We forgot to make the image public (by default new ones gets pushed as private). Will fix up on monday.

**Comment by mdallaire** [comment]
Great, thank you for the quick answer. I will get this going next week then!

**Comment by frezbo** [comment]
> Great, thank you for the quick answer. I will get this going next week then!

This should be fixed now
