### ISSUE TITLE
Documentation issue with iscsi docs

### ISSUE THREAD

**Issue by skandragon** [siderolabs/extensions#75]
I was not sure where to list this issue, but it seems like a general doc issue for installing the iscsi extension at least.

https://www.talos.dev/v1.2/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva/

This page shows this yaml:

```
- op: add
  path: /machine/install/extensions
  value:
    - image: ghcr.io/siderolabs/iscsi-tools:
```

However, this is not proper (does not parse) and if you were to just remove the colon, it also fails to upgrade, and the upgrade ends up in "locked" state, which I don't know how to get out of other than fully rebooting.

I changed the image to `ghcr.io/siderolabs/iscsi-tools:latest` which also seemed to fail.  Using `ghcr.io/siderolabs/iscsi-tools:v0.1.1` worked:

```
NODE          NAMESPACE   TYPE              ID                                          VERSION   NAME          VERSION
10.45.101.1   runtime     ExtensionStatus   000.ghcr.io-siderolabs-iscsi-tools-v0.1.1   1         iscsi-tools   v0.1.1
```

**Comment by frezbo** [comment]
Sorry, we had an issue with the docs publishing. This is fixed now
